app:
    authorizedRedirectUris: '[http://localhost:8081/oauth2/redirect]'
    tokenExpirationMsec: 864000000
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
bezkoder:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: bezKoderSecretKey
proxy-target-class: true
server:
    port: 8084
spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/testDB
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                enable_lazy_load_no_trans: true
                jdbc:
                    lob: non_contextual_creation=true
    mail:
        host: smtp.gmail.com
        password: sahsdggjcjjyngkc
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: Nataschandreeva83@gmail.com
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 374981250488-l62bbdgt7n79c6hgq5nabamug7ahfdha.apps.googleusercontent.com
                        client-secret: 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
                        scope: '[email, profile]'
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
